In [271]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, RidgeCV, LassoCV, ElasticNetCV
from sklearn.metrics import mean_squared_error, make_scorer
from scipy.stats import skew
from scipy import stats
import csv

In [253]:
df_train = pd.read_csv("data/train.csv")
df_test = pd.read_csv("data/test_full.csv")

## Requirement 1 -  Investigate and preprocess the dataset

#### Search and eliminate duplicate (id) data

In [254]:
df_train.drop_duplicates(subset="Id", keep = False, inplace = True)
df_test.drop_duplicates(subset="Id", keep = False, inplace = True)

#### Look for outliers in (intuitively) relevant features (e.g. GrLivArea). 
Eliminate or transform the features such that the outliers pose less difficulty for regression models.

In [255]:
# columns that intuitively influence the target variable and are also numeric so they can present outliers
columns_of_interest = ['LotArea', 'YearBuilt', 'GrLivArea']

# calculate the z-score of those columns along their respective column
# and if the score is above a certain threshold, remove the rows
threshold = 3

z_train = np.abs(stats.zscore(df_train[columns_of_interest]))
df_train = df_train[(z_train < threshold).all(axis = 1)]

#### Replace the numerical features that are actually categories (e.g. MSSubClass, MoSold).

In [256]:
ms_subclass_dict = {
    20: '1-STORY 1946 & NEWER ALL STYLES',
    30: '1-STORY 1945 & OLDER',
    40: '1-STORY W/FINISHED ATTIC ALL AGES',
    45: '1-1/2 STORY - UNFINISHED ALL AGES',
    50: '1-1/2 STORY FINISHED ALL AGES',
    60: '2-STORY 1946 & NEWER',
    70: '2-STORY 1945 & OLDER',
    75: '2-1/2 STORY ALL AGES',
    80: 'SPLIT OR MULTI-LEVEL',
    85: 'SPLIT FOYER',
    90: 'DUPLEX - ALL STYLES AND AGES',
   120: '1-STORY PUD (Planned Unit Development) - 1946 & NEWER',
   150: '1-1/2 STORY PUD - ALL AGES',
   160: '2-STORY PUD - 1946 & NEWER',
   180: 'PUD - MULTILEVEL - INCL SPLIT LEV/FOYER',
   190: '2 FAMILY CONVERSION - ALL STYLES AND AGES'
}

mo_sold_dict = {
    1: 'january',
    2: 'february',
    3: 'march',
    4: 'april',
    5: 'may',
    6: 'june',
    7: 'july',
    8: 'august',
    9: 'september',
    10: 'october',
    11: 'november',
    12: 'december'
}

df_train.replace({'MoSold': mo_sold_dict, 'MSSubClass': ms_subclass_dict}, inplace=True)
df_test.replace({'MoSold': mo_sold_dict, 'MSSubClass': ms_subclass_dict}, inplace=True)

#### Encode ordered categorical features with ordered numbers (e.g. 0, 1, 2 3 ...) whenever possible.

In [257]:
quality_dict = {
    'NA': 1,
    'Po': 2,
    'Fa': 3,
    'TA': 4,
    'Gd': 5,
    'Ex': 6,
    
    'Unf': 2,
    'RFn': 3,
    'Fin': 4,
    
    'Sal': 1,
    'Sev': 2,
    'Maj2': 3,
    'Maj1': 4,
    'Mod': 5,
    'Min1': 6,
    'Min2': 7,
    'Typ': 8,
    
    'LwQ': 3,
    'Rec': 4,
    'BLQ': 5,
    'ALQ': 6,
    'GLQ': 7,
    
    'No': 2,
    'Mn': 3,
    'Av': 4,
    'Gd': 5
}

df_train.replace({
    'PoolQC': quality_dict, 
    'GarageCond': quality_dict, 
    'GarageQual': quality_dict, 
    'GarageFinish': quality_dict, 
    'FireplaceQu': quality_dict, 
    'Functional': quality_dict, 
    'KitchenQual': quality_dict, 
    'HeatingQC': quality_dict, 
    'BsmtFinType2': quality_dict, 
    'BsmtFinType1': quality_dict, 
    'BsmtExposure': quality_dict, 
    'BsmtCond': quality_dict,
    'BsmtQual': quality_dict, 
    'ExterCond': quality_dict, 
    'ExterQual': quality_dict
}, inplace=True)

df_test.replace({
    'PoolQC': quality_dict, 
    'GarageCond': quality_dict, 
    'GarageQual': quality_dict, 
    'GarageFinish': quality_dict, 
    'FireplaceQu': quality_dict, 
    'Functional': quality_dict, 
    'KitchenQual': quality_dict, 
    'HeatingQC': quality_dict, 
    'BsmtFinType2': quality_dict, 
    'BsmtFinType1': quality_dict, 
    'BsmtExposure': quality_dict, 
    'BsmtCond': quality_dict,
    'BsmtQual': quality_dict, 
    'ExterCond': quality_dict, 
    'ExterQual': quality_dict
}, inplace=True)

#### Handle missing data
For some missing numerical features the global average or median might be a good choice, while other features may require a local the usage of a local average/median.

In [258]:
# finding the percentage of missing data in the columns that have missing data
percentage = (df_train.isnull().sum()/df_train.isnull().count()).sort_values(ascending=False)

# remove all columns that have more than 40 percent missing data
df_train.drop(percentage[percentage > 0.4].index, axis=1, inplace=True)

# complete the rest with the global mean
df_train.fillna(df_train.mean(), inplace=True)
df_test.fillna(df_test.mean(), inplace=True)

## Requirement 2 - Prepare by generating new features in the following ways

#### You can simplify some features (e.g. OverallQual) by quantifying it as scores for low, average, high.

In [259]:
fuzzy_dict = {
    10: 'high',
    9: 'high',
    8: 'high',
    7: 'average',
    6: 'average',
    5: 'average',
    4: 'low',
    3: 'low',
    2: 'low',
    1: 'low'
}

df_train.replace({
    'OverallQual': fuzzy_dict,
    'OverallCond': fuzzy_dict
}, inplace=True)

df_test.replace({
    'OverallQual': fuzzy_dict,
    'OverallCond': fuzzy_dict
}, inplace=True)

fuzzy_dict = {
    'high': 3,
    'average': 2,
    'low': 1
}

df_train.replace({
    'OverallQual': fuzzy_dict,
    'OverallCond': fuzzy_dict
}, inplace=True)

df_test.replace({
    'OverallQual': fuzzy_dict,
    'OverallCond': fuzzy_dict
}, inplace=True)

#### Encode categorical features as one-hot-encodings. You can use pandas.get_dummies method.

In [260]:
categorical_features = ['MSSubClass', 'MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 
                        'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 
                        'Exterior1st', 'Exterior2nd', 'Foundation', 'Heating', 'Electrical', 
                        'GarageType', 'SaleType', 'SaleCondition']

for category in categorical_features:
    df_train[category] = pd.Categorical(df_train[category])
    dfDummies = pd.get_dummies(df_train[category], prefix = 'category')
    df_train = pd.concat([df_train, dfDummies], axis=1)
    
    df_test[category] = pd.Categorical(df_test[category])
    dfDummies = pd.get_dummies(df_test[category], prefix = 'category')
    df_test = pd.concat([df_test, dfDummies], axis=1)

## Requirement 3 -  Analyze, visualize and select features

####  Correlation plot and ﬁnd the top 20 most relevant features, including previously generated features.

In [261]:
corr_matrix = df_train.corr()
# df_train_v2 = df_train.drop(df_train.columns.difference(corr_matrix['SalePrice'][corr_matrix['SalePrice'] > 0.27].index), axis=1)
corr_matrix['SalePrice'].sort_values(ascending=False)
# df_train_v2
# corr_matrix['SalePrice'][corr_matrix['SalePrice'] > 0.27].sort_values(ascending=False)

# exterqual, grlivarea, overallqual, kitchenqual, bsmtqual
# garagecars, totalbsmtsf, 1stflrsf, yearbuild
# fullbath, yearremodadd, foundation, totrmsabvgrd, garagefinish
# garageyrblt, masvnrarea, fireplaces, heatingqc, neighborhood, saletype

# ignore GarageArea because is similar to GarageCars


interest_numerical_features = ['ExterQual', 'GrLivArea', 'OverallQual', 'KitchenQual', 'BsmtQual', 'GarageCars',
                     'TotalBsmtSF', '1stFlrSF', 'YearBuilt', 'FullBath', 'YearRemodAdd', 'TotRmsAbvGrd',
                     'GarageFinish', 'GarageYrBlt', 'MasVnrArea', 'Fireplaces', 'HeatingQC', 'SalePrice']
interest_categorical_features = ['Neighborhood', 'Foundation', 'SaleType']

df_train_final = df_train[interest_numerical_features]
df_test_final = df_test[interest_numerical_features]

for category in interest_categorical_features:
    dfDummies = pd.get_dummies(df_train[category], prefix = category)
    df_train_final = pd.concat([df_train_final, dfDummies], axis=1)
    
    dfDummies = pd.get_dummies(df_test[category], prefix = category)
    df_test_final = pd.concat([df_test_final, dfDummies], axis=1)

#### Data distribution plots for top 20 most relevant features.

In [262]:
df_train_final

,ExterQual,GrLivArea,OverallQual,KitchenQual,BsmtQual,GarageCars,TotalBsmtSF,1stFlrSF,YearBuilt,FullBath,...,Foundation_Wood,SaleType_COD,SaleType_CWD,SaleType_Con,SaleType_ConLD,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD
0,5,1710,2,5,5.000000,2,856,856,2003,2,...,0,0,0,0,0,0,0,0,0,1
1,4,1262,2,4,5.000000,2,1262,1262,1976,2,...,0,0,0,0,0,0,0,0,0,1
2,5,1786,2,5,5.000000,2,920,920,2001,2,...,0,0,0,0,0,0,0,0,0,1
3,4,1717,2,5,4.000000,3,756,961,1915,1,...,0,0,0,0,0,0,0,0,0,1
4,5,2198,3,5,5.000000,3,1145,1145,2000,2,...,0,0,0,0,0,0,0,0,0,1
5,4,1362,2,4,5.000000,2,796,796,1993,1,...,1,0,0,0,0,0,0,0,0,1
6,5,1694,3,5,6.000000,2,1686,1694,2004,2,...,0,0,0,0,0,0,0,0,0,1
7,4,2090,2,4,5.000000,2,1107,1107,1973,2,...,0,0,0,0,0,0,0,0,0,1
8,4,1774,2,4,4.000000,2,952,1022,1931,2,...,0,0,0,0,0,0,0,0,0,1
9,4,1077,2,4,4.000000,1,991,1077,1939,1,...,0,0,0,0,0,0,0,0,0,1
10,4,1040,2,4,4.000000,1,1040,1040,1965,1,...,0,0,0,0,0,0,0,0,0,1
11,6,2324,3,6,6.000000,3,1175,1182,2005,3,...,0,0,0,0,0,0,0,1,0,0
12,4,912,2,4,4.000000,1,912,912,1962,1,...,0,0,0,0,0,0,0,0,0,1
13,5,1494,2,5,5.000000,3,1494,1494,2006,2,...,0,0,0,0,0,0,0,1,0,0
14,4,1253,2,4,4.000000,1,1253,1253,1960,1,...,0,0,0,0,0,0,0,0,0,1
15,4,854,2,4,4.000000,2,832,854,1929,1,...,0,0,0,0,0,0,0,0,0,1
16,4,1004,2,4,4.000000,2,1004,1004,1970,1,...,0,0,0,0,0,0,0,0,0,1
17,4,1296,1,4,4.575126,2,0,1296,1967,2,...,0,0,0,0,0,0,0,0,0,1
18,4,1114,2,5,4.000000,2,1114,1114,2004,1,...,0,0,0,0,0,0,0,0,0,1
19,4,1339,2,4,4.000000,1,1029,1339,1958,1,...,0,1,0,0,0,0,0,0,0,0
20,5,2376,3,5,6.000000,3,1158,1158,2005,3,...,0,0,0,0,0,0,0,1,0,0
21,4,1108,2,5,4.000000,1,637,1108,1930,1,...,0,0,0,0,0,0,0,0,0,1
22,5,1795,3,5,5.000000,2,1777,1795,2002,2,...,0,0,0,0,0,0,0,0,0,1
23,4,1060,2,4,5.000000,2,1040,1060,1976,1,...,0,0,0,0,0,0,0,0,0,1
24,4,1060,2,5,4.000000,1,1060,1060,1968,1,...,0,0,0,0,0,0,0,0,0,1
25,5,1600,3,5,5.000000,3,1566,1600,2007,2,...,0,0,0,0,0,0,0,0,0,1
26,4,900,2,5,4.000000,2,900,900,1951,1,...,0,0,0,0,0,0,0,0,0,1
27,5,1704,3,5,6.000000,3,1704,1704,2007,2,...,0,0,0,0,0,0,0,0,0,1
28,4,1600,2,4,4.000000,1,1484,1600,1957,1,...,0,0,0,0,0,0,0,0,0,1
29,4,520,1,3,4.000000,1,520,520,1927,1,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,5,1838,2,4,5.000000,2,732,734,2005,2,...,0,0,0,0,0,0,0,0,0,1
1431,4,958,2,4,5.000000,2,958,958,1976,2,...,0,0,0,0,0,0,0,0,0,1
1432,4,968,1,4,4.000000,1,656,968,1927,2,...,0,0,0,0,0,0,0,0,0,1
1433,4,1792,2,4,5.000000,2,936,962,2000,2,...,0,0,0,0,0,0,0,0,0,1
1434,4,1126,2,4,4.000000,2,1126,1126,1977,2,...,0,0,0,0,0,0,0,0,0,1
1435,5,1537,2,5,4.000000,2,1319,1537,1962,1,...,0,1,0,0,0,0,0,0,0,0
1436,4,864,1,4,4.000000,2,864,864,1971,1,...,0,0,0,0,0,0,0,0,0,1
1437,6,1932,3,6,6.000000,3,1932,1932,2008,2,...,0,0,0,0,0,0,0,1,0,0
1438,4,1236,2,4,4.000000,2,912,1236,1957,1,...,0,0,0,0,0,0,0,0,0,1
1439,4,1725,2,4,4.000000,2,539,1040,1979,2,...,0,0,0,0,0,0,0,0,0,1
1440,4,2555,2,4,6.000000,2,588,1423,1922,2,...,0,0,0,0,0,0,0,0,0,1
1441,5,848,2,5,5.000000,2,848,848,2004,1,...,0,0,0,0,0,0,0,0,0,1
1442,6,2007,3,6,6.000000,3,1017,1026,2008,2,...,0,0,0,0,0,0,0,0,0,1
1443,4,952,2,3,4.000000,1,952,952,1916,1,...,0,0,0,0,0,0,0,0,0,1
1444,5,1422,2,5,5.000000,2,1422,1422,2004,2,...,0,0,0,0,0,0,0,0,0,1
1445,4,913,2,4,4.000000,1,814,913,1966,1,...,0,0,0,0,0,0,0,0,0,1
1446,4,1188,2,4,4.000000,1,1188,1188,1962,1,...,0,0,0,0,0,0,0,0,0,1
1447,5,2090,3,5,5.000000,2,1220,1220,1995,2,...,0,0,0,0,0,0,0,0,0,1
1448,4,1346,1,4,3.000000,1,560,796,1910,1,...,0,0,0,0,0,0,0,0,0,1
1449,4,630,2,6,5.000000,0,630,630,1970,1,...,0,0,0,0,0,0,0,0,0,1
1450,4,1792,2,4,5.000000,0,896,896,1974,2,...,0,0,0,0,0,0,0,0,0,1
1451,5,1578,3,6,5.000000,3,1573,1578,2008,2,...,0,0,0,0,0,0,0,1,0,0
1452,4,1072,2,4,5.000000,2,547,1072,2005,1,...,0,0,0,0,0,0,0,0,0,1
1453,4,1140,2,4,5.000000,0,1140,1140,2006,1,...,0,0,0,0,0,0,0,0,0,1
1454,5,1221,2,5,5.000000,2,1221,1221,2004,2,...,0,0,0,0,0,0,0,0,0,1
1455,4,1647,2,4,5.000000,2,953,953,1999,2,...,0,0,0,0,0,0,0,0,0,1
1456,4,2073,2,4,5.000000,2,1542,2073,1978,2,...,0,0,0,0,0,0,0,0,0,1
1457,6,2340,2,5,4.000000,1,1152,1188,1941,2,...,0,0,0,0,0,0,0,0,0,1
1458,4,1078,2,5,4.000000,1,1078,1078,1950,1,...,0,0,0,0,0,0,0,0,0,1
1459,5,1256,2,4,4.000000,1,1256,1256,1965,1,...,0,0,0,0,0,0,0,0,0,1

#### 5 Lasso regression plots for 5 diﬀerent values for α.

#### Select all relevant features that result from the points above

In [263]:
df_train_final.isnull().sum()

ExterQual               0
GrLivArea               0
OverallQual             0
KitchenQual             0
BsmtQual                0
GarageCars              0
TotalBsmtSF             0
1stFlrSF                0
YearBuilt               0
FullBath                0
YearRemodAdd            0
TotRmsAbvGrd            0
GarageFinish            0
GarageYrBlt             0
MasVnrArea              0
Fireplaces              0
HeatingQC               0
SalePrice               0
Neighborhood_Blmngtn    0
Neighborhood_Blueste    0
Neighborhood_BrDale     0
Neighborhood_BrkSide    0
Neighborhood_ClearCr    0
Neighborhood_CollgCr    0
Neighborhood_Crawfor    0
Neighborhood_Edwards    0
Neighborhood_Gilbert    0
Neighborhood_IDOTRR     0
Neighborhood_MeadowV    0
Neighborhood_Mitchel    0
Neighborhood_NAmes      0
Neighborhood_NPkVill    0
Neighborhood_NWAmes     0
Neighborhood_NoRidge    0
Neighborhood_NridgHt    0
Neighborhood_OldTown    0
Neighborhood_SWISU      0
Neighborhood_Sawyer     0
Neighborhood_SawyerW    0
Neighborhood_Somerst    0
Neighborhood_StoneBr    0
Neighborhood_Timber     0
Neighborhood_Veenker    0
Foundation_BrkTil       0
Foundation_CBlock       0
Foundation_PConc        0
Foundation_Slab         0
Foundation_Stone        0
Foundation_Wood         0
SaleType_COD            0
SaleType_CWD            0
SaleType_Con            0
SaleType_ConLD          0
SaleType_ConLI          0
SaleType_ConLw          0
SaleType_New            0
SaleType_Oth            0
SaleType_WD             0
dtype: int64

## Requirement 4 - Train a regression model able to predict the house prices

#### First implement the a basic regression model and compute its accuracy.

In [264]:
X = pd.DataFrame(df_train_final[df_train_final.columns.difference(['SalePrice'])])
y = pd.DataFrame(df_train_final['SalePrice'])
model = LinearRegression()
model.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

#### Modify the model to improve its accuracy.

In [265]:
X_test = pd.DataFrame(df_test_final[df_test_final.columns.difference(['SalePrice'])])
y_test = pd.DataFrame(df_test_final['SalePrice'])

####  Use k-fold cross-validation to avoid overﬁtting and select best parameters.

In [241]:
model.score(X_test, y_test)

-20.316821776085604

#### Test your model and plot train and test learning curves.

In [273]:
predictions = model.predict(X_test)
predictions

array([[104751.6146491 ],
       [151135.20061634],
       [175949.6328402 ],
       ...,
       [155120.48388954],
       [117043.54286959],
       [210031.29757512]])

In [275]:
header_row = ['Id', 'SalePrice']
rows = []

counter = 1461
for prediction in predictions:
    row = []
    row.append(counter)
    counter += 1
    row.append(prediction.item())
    rows.append(row)


with open('data/testy_test.csv', 'w', newline='') as csv_file:
    csv_writer = csv.writer(csv_file)
    csv_writer.writerow(header_row)
    for value in rows:
        csv_writer.writerow(value)